name: Area Pod Issue Triage
description: A GitHub action for handling Area Pod Issue Triage events

inputs:
  GITHUB_TOKEN:
    default: ${{ github.token }}
  issue:
    description: The issue number to triage
    required: true
    type: number
  action:
    description: The event action performed
    required: true
  assignee:
    description: The assignee (assigned or unassigned)
  label:
    description: The label (labeled or unlabeled)

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/github-actions/areapods:main
  args: [
    "issue-triage",
    "--issue",    "${{ inputs.issue }}",
    "--action",   "${{ inputs.action }}",
    "--assignee", "${{ inputs.assignee }}",
    "--label",    "${{ inputs.label }}",
  ]
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
