name: Area Pod Issue Triage
description: A GitHub action for handling Area Pod Issue Triage events

inputs:
  issue:
    description: The issue number to triage
    required: true
    type: number
  action:
    description: The event action performed
    required: true
    type: string
  assignee:
    description: The assignee (assigned or unassigned)
    required: false
    type: string
  label:
    description: The label (labeled or unlabeled)
    required: false
    type: string

env:
  GITHUB_TOKEN: ${{ github.token }}

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/github-actions/areapods:main
  args: [
    "issue-triage",
    "--repo",     "${{ inputs.repo     }}",
    "--issue",    "${{ inputs.issue    }}",
    "--action",   "${{ inputs.action   }}",
    "--assignee", "${{ inputs.assignee }}",
    "--label",    "${{ inputs.label    }}",
  ]
  env:
    GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
