name: .NET Org Area Pod Issue Triage
description: A GitHub action that drives the .NET org's area pod issue triage process

inputs:
  GITHUB_TOKEN:
    description: The GITHUB_TOKEN secret to use for connecting to GitHub APIs
    required: true
    default: ${{ github.token }}
  issue:
    description: The issue number to triage
    required: true
    type: number
  action:
    description: The event action performed
    required: true
    type: choice
    options:
    - opened
    - closed
    - transferred
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - milestoned
    - demilestoned
  assignee:
    description: The assignee (assigned or unassigned)
    required: false
  label:
    description: The label (labeled or unlabeled)
    required: false

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/action-playground/areapod-issuetriage:main
  args: [
    "--issue", "${{ inputs.issue }}",
    "--action", "${{ inputs.action }}",
    "--assignee", "${{ inputs.assignee }}",
    "--label", "${{ inputs.label }}",
  ]
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
