name: Area Pod Issue Triage

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

on:
  issues:
    types: [opened, closed, transferred, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

  workflow_call:
    inputs:
      issue:
        description: Issue number
        required: true
        type: number
      action:
        description: The event action to simulate
        required: true
        type: string
      assignee:
        description: The assignee (assigned or unassigned)
        required: false
        type: string
      label:
        description: The label (labeled or unlabeled)
        required: false
        type: string

  workflow_dispatch:
    inputs:
      issue:
        description: Issue number
        required: true
        type: number
      action:
        description: The event action to simulate
        required: true
        type: choice
        options: [opened, closed, transferred, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]
      assignee:
        description: The assignee (assigned or unassigned)
        required: false
        type: string
      label:
        description: The label (labeled or unlabeled)
        required: false
        type: string

jobs:
  areapod-issuetriage:
    runs-on: ubuntu-latest

    steps:
      - name: Area Pod Issue Triage
        uses: jeffhandley/github-actions/actions/areapods/issue-triage@main
        with:
          owner:    ${{ github.event.repository.owner.login            }}
          repo:     ${{ github.event.repository.name                   }}
          issue:    ${{ inputs.issue    || github.event.issue.number   }}
          action:   ${{ inputs.action   || github.event.action         }}
          assignee: ${{ inputs.assignee || github.event.assignee.login }}
          label:    ${{ inputs.label    || github.event.label.name     }}
