name: "Labeler: Authors"

on:
  issues:
    types: [opened]

  workflow_call:
    inputs:
      issue:
        type: number
        required: true
      authors:
        type: string
        required: true
      label:
        type: string
        required: true
  
  workflow_dispatch:
    inputs:
      issue:
        description: The issue number to process
        type: number
        required: true
      authors:
        description: The authors whose issues get labeled (separated by spaces)
        type: string
        required: true
        default: jeffhandley eilon heng-liu
      label:
        description: The label to apply for the specified authors
        type: string
        required: true
        default: team-member

jobs:
  authors:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: authors
        uses: jeffhandley/github-actions/actions/labeler/authors@main
        with:
          issue:   ${{ fromJson(inputs.issue  || github.event.number) }}
          authors: ${{ inputs.authors         || 'jeffhandley eilon heng-liu' }}
          label:   ${{ inputs.label           || 'team-member' }}
