name: "Publish: backlog"

on:
  push:
    branches: [ main ]
    paths: [ 'src/AreaPods/**' ]

  pull_request:
    branches: [ main ]
    paths: [ 'src/AreaPods/**' ]

  workflow_dispatch:

jobs:
  publish-action:
    uses: jeffhandley/github-actions/.github/workflows/publish-action.yml@${{ github.ref_name }}
    with:
      action_name: areapods
      action_folder: ./src/AreaPods
