name: "Publish: backlog"

on:
  push:
    branches: [ main ]
    paths: [ 'src/Backlog/**' ]

  pull_request:
    branches: [ main ]
    paths: [ 'src/Backlog/**' ]

  workflow_dispatch:

jobs:
  publish-action:

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/publish-action.yml

    with:
      action_name: backlog
      action_folder: Backlog
