name: "Publish: labeler"

on:
  push:
    branches: [ main ]
    paths: [ 'src/Labeler/**', 'src/Dockerfile' ]

  pull_request:
    branches: [ main ]
    paths: [ 'src/Labeler/**', 'src/Dockerfile' ]

  workflow_dispatch:

jobs:
  publish-action:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/publish-action.yml
    with:
      action_name: labeler
      action_folder: Labeler
