name: "Publish: issue-labeler"

on:
  push:
    branches: [ main ]
    paths: [ 'src/IssueLabeler/**', 'src/Dockerfile' ]

  pull_request:
    branches: [ main ]
    paths: [ 'src/IssueLabeler/**', 'src/Dockerfile' ]

  workflow_dispatch:

jobs:
  publish-action:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/publish-action.yml
    with:
      action_name: issue-labeler
      action_folder: IssueLabeler
