# This workflow looks for trending issues and applies a label to them
# Issues are considered trending if they receive a significant number
# of positive reactions within a period of time

name: Find and label trending issues

on:
  schedule:
  - cron: '* * * * *'

  workflow_call:
    inputs:
      reactions:
        required: true
        type: number
      days:
        required: true
        type: number
      label:
        required: true
        type: string
  
  workflow_dispatch:
    inputs:
      reactions:
        description: The minimum number of positive reactions (from unique users)
        required: true
        type: number
        default: 5
      days:
        description: The maximum number of days within which the reactions need to occur
        required: true
        type: number
        default: 7
      label:
        description: The label to apply for trending issues
        required: true
        type: string
        default: 'trending'

jobs:
  trending-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Find and label trending issues
      run: |
        echo "Finding trending issues..."
        echo "  Reactions: ${{ inputs.reactions || 5          }}"
        echo "  Days:      ${{ inputs.days      || 7          }}"
        echo "  Label:     ${{ inputs.label     || 'trending' }}"
